// react-project/src/App.jsx
import React, { useState, useEffect } from 'react'
import logo from './logo.svg';
import './App.css';

function App() {

  const [username, setUsername] = useState('')

  const receiveMsgHandler = ({ data }) => {
    if (data?.source !== 'main') {
      return;
    }
    console.log('React received: ', data)
    setUsername(data?.username)
  }
  
  useEffect(
    () => {
      console.log('React: Listening message from main...');
      window.addEventListener('message', receiveMsgHandler);

      return () => {
        window.removeEventListener('message', receiveMsgHandler)
      }
    },
    []
  )

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        一个 React 项目
        <h3>欢迎，{username}</h3>
      </header>
    </div>
  );
}

export default App;

// vue3-project/src/App.vue
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <HelloWorld msg="一个 Vue3.0 项目"/>
  <h3>欢迎，{{username}}</h3>
</template>

<script>
import {
  ref,
  onMounted,
  defineComponent,
} from 'vue';
import HelloWorld from './components/HelloWorld.vue'

const receiveMessage = (updateUsername) => {

  const receiveMsgHandler = ({ data }) => {
    if (data?.source !== 'main') {
      return;
    }
    console.log('Vue3 received: ', data)
    updateUsername(data?.username)
  }

  onMounted(() => {
    console.log('Vue3: Listening message from main...');
    window.addEventListener('message', receiveMsgHandler);
  });
};

export default defineComponent({
  name: 'App',
  components: {
    HelloWorld
  },
  setup() {
    const username = ref('');
    console.log('username', username);

    const updateUsername = (val) => {
      username.value = val
    }

    receiveMessage(updateUsername)

    return {
      username,
    }
  }
})
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
